### PR TITLE
8.2.0

### PR DESCRIPTION
**Pull request by thysultan**
-Addition of an ESM module bundle.
- Improvement to typescript definition.
- Improvement to minimum DOM operation count of the reconciler.

There's nothing new as far as API is concerned but the addition of the distribution esm module bundle might merit a minor version bump... Not sure.

### CODE REVIEW

**Comment by leeoniya** [comment]
i'll probably use https://github.com/webcaetano/shuffle-seed for https://github.com/leeoniya/domvm/issues/190

**Comment by Zolmeister** [comment]
@leeoniya I'd just use https://github.com/davidbau/seedrandom directly

**Comment by leeoniya** [comment]
or presumably https://gist.github.com/blixt/f17b47c62508be59987b

**Comment by thysultan** [comment]
@leeoniya Did you find any vdom libs that fuzz their reconciler while working on [leeoniya/domvm#190](https://github.com/leeoniya/domvm/issues/190) ?

**Comment by leeoniya** [comment]
> Did you find any vdom libs that fuzz their reconciler

no, but i'm fairly certain it would reveal a bunch of unhandled cases across many vdom libs. the goal of the fuzzing is to validate the correctness of the reconciler first (this is easy by just serializing the vtree vs innerHTML). i think 10k rounds with various "strengths" of fuzzing would be good to at least add new regression cases without inventing them by hand. it would be impractical to actually add these cases to the test suite, but at minimum it would help add regression tests or narrow down problematic scenarios.

second, validate how many and which dom ops these reconciliations invoke and compare it to the "ideal", hopefully validated against more thorough and likely slower algos. domvm's tests check for both expected ops and correct final dom.

> while working on leeoniya/domvm#190 ?

i'm not working on this yet

**Comment by thysultan** [comment]
>i think 10k rounds with various "strengths" of fuzzing would be good to at least add new regression cases without inventing them by hand.

At around 1,000,000 cases Chrome(at least on my machine crashes), though i did manage ~100k without a crash. Which brings up the question of finding the right balance between the increased time for running these tests vs no. of cases.

**Comment by leeoniya** [comment]
fuzzing is meant to find problems before the problems find the users. it's more of a proactive method of regression testing. it's more suited for identifying edge cases and CI rather than being a permanent fixture in tests. i plan to use it as a tool rather than adding 10k seeds to test for each commit. it's gonna be important to have control over shuffle/mutation thoroughnesss (fuzzing strength) to eg not have to wait for a random case of few mutations, but instead have many tests of few mutations/reorders. with careful control even 10k may be excessive.

**Pull request merged**
